//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_for_Control_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDetails
    {
        public int TreatmentID { get; set; }
        public int AppointmentID { get; set; }
        public string TreatmentDetails { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
