//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_for_Control_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clininc
    {
        public int Id_clinic { get; set; }
        public byte[] Clinic_Image { get; set; }
        public string Clininc_Name { get; set; }
        public string Clininc_Description { get; set; }
        public string Annex { get; set; }
        public string principle { get; set; }
        public string Clininc_Address { get; set; }
    }
}
