//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_for_Control_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GESTION_DENTAL_CLINICEntities2 : DbContext
    {
        public GESTION_DENTAL_CLINICEntities2()
            : base("name=GESTION_DENTAL_CLINICEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<AppointmentDetails> AppointmentDetails { get; set; }
        public virtual DbSet<Treatment> Treatment { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Dentist> Dentist { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Clininc> Clininc { get; set; }
    }
}
