<?xml version="1.0" encoding="utf-8"?><Database Name="GESTION_DENTAL_CLINIC" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=GESTION_DENTAL_CLINIC;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="Project_for_Control_2.Properties.Settings" SettingsPropertyName="GESTION_DENTAL_CLINICConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbUser" Member="tbUser">
    <Type Name="tbUser">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dateofbirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Created at]" Member="Created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Created by]" Member="Created_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>